### ISSUE TITLE
[Finish] 2.4

### ISSUE THREAD

**Issue by TexBlock** [VM-Chinese-translate-group/VM-Chinese-Group-Update#8]
# Plan
- [x] remove MinecraftForge side on 1.20.5+
- [x] Update to 1.20.5-1.20.6
- [x] Use platform's native api
- [x] Redesign of the mod icon
- [x] 1.19.4 is moving to EOL (end of life)
- [x] Fix auto upload mod action (CurseForge and Modrinth mod files are empty -> only 10b 1024b=1kb) 
- [x] 1.20.2-1.20.4 branch Neoforge mods.toml rename to neoforge.mods.toml   -- 2024-05-21 Wulian added

**Comment by Wulian233** [comment]
wow! Redesign mod icon!

**Comment by TexBlock** [comment]
> wow! Redesign mod icon! 其他bug: 1.19.4 分支action不会上传forginx版

这好像不用修了，1.19.4要eol了

**Comment by TexBlock** [comment]
> 服务端安装本模组时，每25分钟发送一次的消息会同步发送给所有玩家（也是同一天消息），计时25分钟使用服务器的开机时间，也许需要做客户端 / 服务端 判断与兼容。

需要考虑此功能是否必需
